############################################################
# +------------------------------------------------------+ #
# |                         Notes                        | #
# +------------------------------------------------------+ #
############################################################

# This file allows to configurate PrivateMessage plugin.
# Plugin developped by NiamorOFF (Twitter : @NiamorOFF).

############################################################
# +------------------------------------------------------+ #
# |                    PrivateMessage                    | #
# +------------------------------------------------------+ #
############################################################

# Allow to choose a translation file between English / French.
# Possible parameters: english or french
language: french